### ISSUE TITLE
Deprecation error when installing requirements

### ISSUE THREAD

**Issue by stalltron** [docmarionum1/slack-archive-bot#5]
I get this error when installing the requirements in `slack-archive-bot` and I'm not sure if things are working correctly or not?

```
Collecting six>=1.10.0 (from -r requirements.txt (line 1))
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting slackclient>=1.0.4 (from -r requirements.txt (line 2))
  Using cached slackclient-1.0.9.tar.gz
Collecting websocket-client<1.0a0,>=0.35 (from slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached websocket_client-0.44.0-py2.py3-none-any.whl
Collecting requests<3.0a0,>=2.11 (from slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests<3.0a0,>=2.11->slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests<3.0a0,>=2.11->slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0a0,>=2.11->slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0a0,>=2.11->slackclient>=1.0.4->-r requirements.txt (line 2))
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Installing collected packages: six, websocket-client, urllib3, idna, chardet, certifi, requests, slackclient
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/gq/m3xyqtqs76x264vknt0cg8jr0000gn/T/pip-EmDpZ8-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'


```

**Comment by docmarionum1** [comment]
Related? 

https://github.com/pypa/pip/issues/3165
https://github.com/donnemartin/haxor-news/issues/54


Try `pip install -r requirements.txt --ignore-installed six`
